import 'package:flutter/material.dart';
import 'package:yaml/yaml.dart';

import 'package:holcomb_tree_trail/ui/main_navigation.dart';
import 'package:holcomb_tree_trail/ui/theme.dart';

//import 'package:firebase_core/firebase_core.dart';
//import 'firebase_options.dart'; // This file is generated by `flutterfire configure`


// Create global lists for featured tree list items and pages
var treeIdMap = {};
Map<String, Map<String, String >> treePageData = {};

void main() {

  /* TODO:
    * implement firebase initialization
    * load and verify assets
    * build list of Trees - DONE
    * build pages and routes for every Tree - DONE
  */

  String testYaml = 
    '''
    1-18: "shingle oak"\n10-18: "swamp white oak"\n59-21: "dawn redwood"
    ''';

  /*
   Begin building map of ID to Tree name
   First step reads YAML stream into treeIdMap. Converts list of Maps to a single Map
   Next step builds treePageData that holds everything a page needs 
   */
  var treeIdMap = {};

  try {
    // read the YAML Stream
    var treeDoc = loadYamlStream(testYaml);

    // convert the YamlList into a Map<dynamic, dynamic>
    for (var entry in treeDoc) {
      treeIdMap.addAll(entry);
    }
  }
  catch(e) {
    // TODO better error handling than this
    print("An error occured while loading the YAML manifest!");
    print(e);
  }
  
  try{
    // create treePageData entries for expected trees in the yaml manifest
    for (var id in treeIdMap.keys) {
      /* TODO 
        'body' value will need to be pulled from firebase
        Where should images go?
      */
      treePageData[id] = {'id': id, 'name': treeIdMap[id], 'body': "Body text."};
    }
  }
  catch(e) {
    // TODO better error handling than this
    print("An error occured while building tree info pages!");
    print(e);
  }
  /*
  final storage = FirebaseStorage.instance;
  final storageRef = storage.ref();
  final imageRef = storageRef.child('images/');
  final textRef = storageRef.child('text/');

  var testMap = {'1-18': "shingle oak"};

  for (var id in testMap.keys) {
    
  }
  */


  // begin rendering the app widget, bootstrap the render tree
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Holcomb Tree Trail',
      //theme: ThemeData.from(colorScheme: MaterialTheme.lightScheme(), textTheme: GoogleFonts.latoTextTheme()),
      theme: MaterialTheme().light(),
      //home: HomePage(title: 'Home Page'),
      home: const MainNavigation(), // use MainNavigation instead of HomePage
    );
  }
}