import 'package:flutter/material.dart';
import 'package:holcomb_tree_trail/ui/nav_bar.dart';
import 'package:holcomb_tree_trail/ui/theme.dart';

//import 'package:firebase_core/firebase_core.dart';
//import 'firebase_options.dart'; // This file is generated by `flutterfire configure`

// TODO: implement firebase initialization

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Holcomb Tree Trail',
      //theme: ThemeData.from(colorScheme: MaterialTheme.lightScheme(), textTheme: GoogleFonts.latoTextTheme()),
      theme: MaterialTheme().light(),
      //home: HomePage(title: 'Home Page'),
      home: const MainNavigation(), // use MainNavigation instead of HomePage
    );
  }
}