import 'package:flutter/material.dart';
import 'package:yaml/yaml.dart';

import 'package:holcomb_tree_trail/ui/main_navigation.dart';
import 'package:holcomb_tree_trail/ui/theme.dart';

//import 'package:firebase_core/firebase_core.dart';
//import 'firebase_options.dart'; // This file is generated by `flutterfire configure`


// Create global lists for featured tree list items and pages
var treeIdMap = {};
Map<String, Map<String, String >> treePageData = {};

void main() {

  /* TODO:
    * implement firebase initialization
    * load and verify assets
    * build list of Trees
    * build pages and routes for every Tree
  */

  String testYaml = 
    '''
    1-18: "shingle oak"\n10-18: "swamp white oak"
    ''';

  var treeIdMap = {};

  try {
    var treeDoc = loadYamlStream(testYaml);
    print(treeDoc);

    for (var entry in treeDoc) {
      treeIdMap.addAll(entry);
    }

    print(treeIdMap);
  }
  catch(e) {
    print("An error occured while loading the YAML manifest!");
    print(e);
  }
  
  try{
    for (var id in treeIdMap.keys) {
      treePageData[id] = {'id': id, 'name': treeIdMap[id], 'body': "Body text."};
    }
  }
  catch(e) {
    print("An error occured while building tree info pages!");
    print(e);
  }

  // begin rendering the app widget, bootstrap the render tree
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Holcomb Tree Trail',
      //theme: ThemeData.from(colorScheme: MaterialTheme.lightScheme(), textTheme: GoogleFonts.latoTextTheme()),
      theme: MaterialTheme().light(),
      //home: HomePage(title: 'Home Page'),
      home: const MainNavigation(), // use MainNavigation instead of HomePage
    );
  }
}